# Generated by Django 2.1.7 on 2019-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_id', models.IntegerField()),
                ('enter_r_exit', models.CharField(choices=[('enter', 'enter'), ('exit', 'exit')], max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.TextField(default='startup')),
                ('by', models.IntegerField(default=0)),
            ],
        ),
    ]
