# Generated by Django 2.1.7 on 2019-02-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('booked', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Seats', 'Seats'), ('Auditorium', 'Auditorium'), ('Instruments', 'Instruments'), ('Meeting Halls', 'Meeting Halls'), ('Others', 'Others')], max_length=100)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.Resource'),
        ),
    ]
