# Generated by Django 2.1.7 on 2019-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190216_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
