# Generated by Django 2.1.7 on 2019-02-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20190217_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_items',
            old_name='item_id',
            new_name='itemid',
        ),
        migrations.AddField(
            model_name='order_items',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='cafe.Item'),
            preserve_default=False,
        ),
    ]
