# Generated by Django 2.1.7 on 2019-02-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('dp', models.ImageField(null=True, upload_to='')),
                ('user_type', models.CharField(choices=[('startup_worker', 'startup_worker'), ('admin', 'admin'), ('general', 'general'), ('receptionist', 'receptionist'), ('librarian', 'librarian'), ('canteen_incharge', 'canteen_incharge'), ('others', 'others')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
