# Generated by Django 2.1.7 on 2019-02-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Startup Worker', 'Startup Worker'), ('Admin', 'Admin'), ('Staff', 'Staff')], max_length=100),
        ),
    ]
