# Generated by Django 2.1.7 on 2019-02-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190214_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Startup Worker', 'Startup Worker'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Others', 'Others')], max_length=100),
        ),
    ]
